(function(){
  const formHost=document.getElementById('formHost');
  const cartItems=document.getElementById('cartItems');
  const productCount=document.getElementById('productCount');
  const unitCount=document.getElementById('unitCount');
  const clearCartBtn=document.getElementById('clearCart');
  function normalizeQty(value){const n=parseInt(String(value||'').replace(/[^0-9]/g,''),10);return Number.isFinite(n)?n:0}
  function escapeHTML(str){return String(str).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function getProductName(product){const selectors=['.form-product-name','.form-product-name-detail','.form-product-container .form-product-name','label','.form-product-item'];for(const selector of selectors){const el=product.querySelector(selector);if(el&&el.textContent.trim())return el.textContent.trim().replace(/\s+/g,' ')}return 'Producto'}
  function updateCart(){const qtyInputs=document.querySelectorAll('.form-product-custom_quantity');const selected=[];let units=0;qtyInputs.forEach(input=>{const qty=normalizeQty(input.value);if(qty<=0)return;const product=input.closest('.form-product-item')||input.closest('[data-wrapper-react="true"]')||input.closest('li')||input.parentElement;const name=product?getProductName(product):'Producto';selected.push({name,qty});units+=qty});productCount.textContent=selected.length;unitCount.textContent=units;if(!selected.length){cartItems.textContent='Todavía no seleccionaste productos.';return}cartItems.innerHTML=selected.map(item=>`<div class="cart-item"><strong>${escapeHTML(item.name)}</strong><span class="qty-pill">Cantidad: ${item.qty}</span></div>`).join('')}
  function clearCart(){document.querySelectorAll('.form-product-custom_quantity').forEach(input=>{input.value='0';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new Event('blur',{bubbles:true}))});updateCart()}
  function removeJotformPromo(){Array.from(document.querySelectorAll('a,button,div,footer,p,span')).forEach(el=>{const text=(el.textContent||'').toLowerCase();const href=(el.getAttribute&&el.getAttribute('href')||'').toLowerCase();const promo=text.includes('create your own jotform')||text.includes('now create your own jotform')||text.includes('it’s free')||text.includes("it's free")||href.includes('jotform.com');if(promo){const block=el.closest('.formFooter,.form-footer,footer,div')||el;block.style.display='none'}})}
  function resetCartOnly(){productCount.textContent='0';unitCount.textContent='0';cartItems.textContent='Todavía no seleccionaste productos.'}
  function afterSubmitCleanup(){setTimeout(()=>{resetCartOnly();window.scrollTo({top:0,behavior:'smooth'});removeJotformPromo()},500);setTimeout(removeJotformPromo,1200);setTimeout(removeJotformPromo,2500);setTimeout(removeJotformPromo,4500)}
  function bindEvents(){document.addEventListener('input',e=>{if(e.target&&e.target.classList&&e.target.classList.contains('form-product-custom_quantity'))updateCart()});document.addEventListener('change',e=>{if(e.target&&e.target.classList&&e.target.classList.contains('form-product-custom_quantity'))updateCart()});document.addEventListener('submit',e=>{if(e.target&&e.target.classList&&e.target.classList.contains('jotform-form'))afterSubmitCleanup()},true);document.addEventListener('click',e=>{const target=e.target;if(!target)return;const submitLike=target.closest&&target.closest('button,input[type="submit"]');if(submitLike&&String(submitLike.textContent||submitLike.value||'').toLowerCase().includes('enviar'))afterSubmitCleanup()},true);clearCartBtn.addEventListener('click',clearCart);const observer=new MutationObserver(()=>{removeJotformPromo();updateCart()});observer.observe(document.body,{childList:true,subtree:true})}
  async function loadForm(){try{const response=await fetch('formulario.html',{cache:'no-store'});if(!response.ok)throw new Error('No se pudo cargar formulario.html');const html=await response.text();formHost.innerHTML=html;formHost.querySelectorAll('script').forEach(oldScript=>{const newScript=document.createElement('script');Array.from(oldScript.attributes).forEach(attr=>newScript.setAttribute(attr.name,attr.value));if(oldScript.textContent)newScript.textContent=oldScript.textContent;oldScript.replaceWith(newScript)});setTimeout(updateCart,700);setTimeout(removeJotformPromo,900)}catch(err){formHost.innerHTML='<div class="load-error">No se pudo cargar el formulario. Revisá que formulario.html esté subido al repositorio.</div>';console.error(err)}}
  bindEvents();loadForm();
})();
